---
- name: Instalação da aplicação na VM2
  hosts: app
  become: yes

  tasks:
    - name: Instalar dependências de sistema (Git, Node.js e npm)
      package:
        name:
          - git
          - nodejs
        state: present
        update_cache: yes

    - name: Clonar repositório da aplicação
      git:
        repo: https://github.com/mayx2/api-produtos.git
        dest: /home/vagrant/api-produtos
        force: yes

    - name: Instalar dependências da aplicação via npm
      shell: npm install
      args:
        chdir: /home/vagrant/api-produtos
